name: Build frontend

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: switch to folder
          run: |
            cd frontend
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
          expo-packager: npm
      - name: install npm
        run: |
          npm install
      - name: run tests
        run: |
          cd frontend
      - name: build frontend
        run: |
          cd frontend
          expo build:web
