name: Deploy Secret-Allergy

on:
  push:
    branches:
      - main

jobs:
  build-frontend:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
            - run: |
              cd frontend
              npm install

      - name: run builds
        run: |
          cd frontend
          expo build:web
      - uses: actions/upload-artifact@v2
        with:
          name: web-build
          path: frontend/web-build/

  build-backend:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - uses: actions/download-artifact@v2
        with:
          name: frontend-build
          path: backend/src/main/resources/static
      - name: Build with Maven
        run: mvn -B package -DskipTests --file backend/pom.xml
      - uses: actions/upload-artifact@v2
        with:
          name: secret-allergy.jar
          path: backend/target/

  deploy:
    name: deploy to heroku
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - uses: actions/checkout@v2
      - name: create target folder
        run: mkdir backend/target
      - uses: actions/download-artifact@v2
        with:
          name: secret-allergy.jar
          path: backend/target
      - name: login to heroku container
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: push docker container to heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:push web -a secret-allergy
      - name: deploy/release docker container to heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release web -a secret-allergy
